# Generated by Django 4.0.6 on 2022-10-29 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('exp', models.CharField(max_length=1000)),
                ('deb', models.IntegerField(default=0)),
                ('cred', models.IntegerField(default=0)),
                ('remain', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ustable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tranactions', models.ManyToManyField(to='main.transaction')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
